# Generated by Django 2.1.1 on 2020-01-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slack_team_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='slack_user_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
